spring:
  application:
  name: certus-eureka-server

server:
  port: 9761

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

eureka:
  instance:
#    prefer-ip-address: true
#    appname: ui-gateway
#    instanceId: ui-gateway:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    enabled: true
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/